micronaut:
  application:
    name: micronaut-starter-basic
  server:
    host: ${HOST:0.0.0.0}
    port: ${PORT:8080}
    cors:
      enabled: true
  security:
    enabled: false
  session:
    http:
      cookie: true
      header: true
  router:
    introspection: true
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: classpath:static
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
